name: Build and Test
on:
  pull_request: {}
  push:
    branches: main
jobs:
  run-build:
    name: Check that the page can be built
    strategy:
      matrix:
        npm-command: ["build"] # todo: add test here once we have tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: true # necessary for the data
          ref: ${{ github.event.workflow_run.head_branch }}
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }} # expires 2024-12-01
          # Regenerate token: https://github.com/settings/tokens/1065933443
          # Update secret with regenerated token https://github.com/Hochfrequenz/ahbesser/settings/secrets/actions/SUBMODULE_ACCESS_TOKEN
          lfs: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install Node.js dependencies
        working-directory: "ahb_viewer"
        run: npm install
      - name: Run ${{ matrix.npm-command }}
        working-directory: "ahb_viewer"
        run: npm run ${{ matrix.npm-command }}
